DONE ! (UNITY BANZAI 🎊)
devmountaintechfest/hackathon-season2 pull request #20
Opened 2022-10-09 12:57 UTC by ShiragaP

;)

2022-10-09 13:07 UTC, ShiragaP commented
## ไม่มีทีมครับ
ทีม "โลก หมุนได้นะครับ"
สมาชิก
- [ShiragaP](https://github.com/ShiragaP)

Repo: [hackathon](https://github.com/ShiragaP/hackathon-season2)

2022-10-09 13:26 UTC, lordbenz commented
อันนี้ในทีมมีกี่คนครับ พอดีอ่านแล้ว งงๆ 555

2022-10-09 13:30 UTC, ShiragaP commented
คนเดียวคนผม 😉

2022-10-09 13:31 UTC, lordbenz commented
555 เคครับ @ShiragaP

2022-10-09 13:34 UTC, rsxss commented
ผมชอบนะครับ

2022-10-09 13:34 UTC, ShiragaP commented
repo?

2022-10-09 13:35 UTC, ShiragaP commented
ชอบกรรมการ?

2022-10-09 13:35 UTC, annibuliful commented
ชอบคุณครับ
ผ่าม ผ้าม

2022-10-09 13:35 UTC, rsxss commented
55555555555555555

2022-10-09 13:37 UTC, annibuliful commented
ไม่ให้ใช้ library แต่มาเป็น engine เลย
ขอวิดีโอ demo ด้วยครับ @ShiragaP

2022-10-09 13:40 UTC, annibuliful commented
แล้วก็เหมือนจะไม่มี json ตอนสุดท้ายด้วย @ShiragaP รบกวนเพิ่มด้วยครับ
https://github.com/devmountaintechfest/hackathon-season2/pull/20/files

<img width="830" alt="Screen Shot 2565-10-09 at 20 39 42" src="https://user-images.githubusercontent.com/5283709/194760135-521339a9-585d-4591-ae20-bc1eb77dc1d1.png">
จะเข้าไปตรวจ m1 pro 32GB ผมค้างไปแล้วววววว

2022-10-09 13:40 UTC, annibuliful commented
ขอตัดคะแนนได้มั๊ยเนี๊ย

2022-10-09 13:42 UTC, ShiragaP commented
ได้ครับ ถึงท่านกรรมการจะตัดคะแนนแต่ผมก็ไม่ตัดใจนะครับ

2022-10-09 13:43 UTC, ShiragaP commented
> ไม่ให้ใช้ library แต่มาเป็น engine เลย ขอวิดีโอ demo ด้วยครับ @ShiragaP

เดียวจัดให้นะครับ

2022-10-09 13:56 UTC, annibuliful commented
demo ส่งเลทไม่เป็นไรครับ แต่ทำmacbook ค้างนี้ไม่น่าให้อภัยอย่างยิ่ง

2022-10-09 14:02 UTC, annibuliful commented
@ShiragaP  มีแบบ video มั๊ยครับขี้เกียจลง unity

2022-10-09 14:03 UTC, annibuliful commented
ให้พวกผมตรวจง่ายๆเถอะนะ

2022-10-09 14:09 UTC, ShiragaP commented
> demo ส่งเลทไม่เป็นไรครับ แต่ทำmacbook ค้างนี้ไม่น่าให้อภัยอย่างยิ่ง
ขออภัยครับอาจจะต้องลองเอา RTX4090 มาต่อกับ M1 ดูครับ ยูทูปน่าจะลื่นขึ้นด้วย 🙏

> @ShiragaP มีแบบ video มั๊ยครับขี้เกียจลง unity
มีครับ กรรมการวัยรุ่นจริง ๆ (Celeron ผมช้านิดหนึงครับ)

2022-10-09 14:22 UTC, ShiragaP commented
![image](https://user-images.githubusercontent.com/10695804/194762045-77467d62-d624-492e-9bd2-b6f841894215.png)
 
เดียวไป Upgrade เป็น Pentium แปปนะครับ

2022-10-09 14:43 UTC, annibuliful commented
อยู่ญี่ปุ่น หวังว่าจะกลับไทยทันนะครับ 5555555

2022-10-10 11:35 UTC, ShiragaP commented
https://user-images.githubusercontent.com/10695804/194857359-56c09616-6d79-4a28-8530-196f37902668.mp4

2022-10-10 11:36 UTC, ShiragaP commented
https://user-images.githubusercontent.com/10695804/194857540-8f77f92d-6e9e-4750-9e45-ab617f8df8a2.mp4

2022-10-10 11:49 UTC, ShiragaP commented
https://user-images.githubusercontent.com/10695804/194859536-d4d71be9-0798-4510-9a34-ee4695c262b6.mp4

2022-10-10 13:00 UTC, annibuliful requested changes
It's very hard to read on web so I will review your PR later

2023-06-04 11:07 UTC, closed without merging